version: "3.9"
services:
  laravel_app:
    build: ./php
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - laravel_db
    networks:
      - frontend_network
      - backend_network

  nginx:
    build: ./nginx
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - laravel_app
    environment:
      NGINX_FPM_HOST: laravel_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - frontend_network
      - backend_network

  laravel_db:
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend_network

  laravel_redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network:
